# Generated by Django 2.0.3 on 2018-04-02 05:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=30)),
                ('goods_pic', models.ImageField(upload_to='df_goods')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods_unit', models.CharField(max_length=10)),
                ('goods_intro', models.CharField(max_length=70)),
                ('goods_detail', tinymce.models.HTMLField()),
                ('goods_click', models.IntegerField()),
                ('type_id', models.IntegerField()),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'goods_type',
            },
        ),
    ]
