# Generated by Django 2.0.3 on 2018-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_pic',
            field=models.ImageField(upload_to='df_goods/'),
        ),
    ]
