# Generated by Django 2.0.3 on 2018-03-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deli_name', models.CharField(max_length=10)),
                ('deli_address', models.CharField(default='', max_length=80)),
                ('deli_postcode', models.CharField(default='', max_length=6)),
                ('deli_phone', models.CharField(default='', max_length=11)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'delivery_address',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_pwd', models.CharField(max_length=20)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('user_phone', models.CharField(default='', max_length=11)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
