# Generated by Django 2.0.3 on 2018-03-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pwd',
            field=models.CharField(max_length=40),
        ),
    ]
