# Generated by Django 2.0.3 on 2018-03-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_auto_20180327_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
